version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    working_directory: ~/project/examples/react-hooks
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build:
    jobs:
      - build_and_test
